[gcp_service_account]
type = "service_account"
project_id = "my-project-21182-468414"
private_key_id = "92198dd24e77c0cad931264330721679722ddafc"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDFTjM69VpfMPkB
+iqHWs1n0tvfJk12RT2uKx7PIwHP6xu/SNjDiGQ15nQlsufbc01+SsAeTUvRxihH
v2hprfHV1YbyHGe0WghV2G6ZTNUHFyRdXqRZfcylzKzteIQYkq1Q/cl1S35bi1iP
2XBUkOBV26ai0x/qPbKBJZthFu5B/4Y+XbU6FXXbgOrihBLsxUa+DmJmHWuccr20
5z2Vx1OTITeISuSR0Ae+lDGM9tlm9F0hmpq8HoIbP8ueH/vAEcBMTdeDX9Y3VOUW
6C1d0hX/MaKfn8jryDYFZbtXRPg90HYtq3U08iwfFn56fcjMRErCDC8+nZrH/4j4
oicSBwOXAgMBAAECggEAS3LU6lXKYh5TCiuEuc/CPlKGm7WE55YguQpqNKFZXw2z
xZjwswzj7Syb+5KHUQaten7RKoU6WhRhcNZD8i1/DdsiSFEOYwwOpe0mld6ok5aI
5F99j28oo7o54nE0akUkm5UAxabBwfXuPsvSRbRE5PAir572VFeVfAdKfH0NTRTh
BjzBQPHcbGQk5lol46HroT2udbeujzLEIWYdSK15hvJ+9ppVc2F+KnGD56jmtoq2
7AFkjw4kR8NqYSVPVjGTrqyU0x8h/EZmK+xbG2+O+bQYG7yf5IBaRQogAXqNPRQj
tDms+XLmpe8tEfp29hq5t2x/AzKkvz9JexNPTo6huQKBgQD/4yNEK+zf8sO80K83
ld/PgaHvGrsWW4wDW6PrShvV3sevO+ApZuoAB+QGIOijO1PD9lgKiISlAEHSwiQ7
bsDLJMi0rMrDvRN/OCC1Pvrrh3hDKD++UF3rO+XOLXC9uGLhFm/vi/AHbeUUwqJs
kjvEUrSlXfig5myvlaGrr4kkswKBgQDFZHRq2Pzm8/WlWzIWWqrrpTeHdHe7FCAS
bnzGN+f7jMa7hBDMC7kEVUUu/t5ZpJHIHs37q3fAi4jgD8RMg7AKc0McZ98r1mGc
mWxz3OfVK0tRT1hSl2iMNe2/jAK4ZSefHkROFsKqddMl8Ijs2ytJ8y+NZQZtsMk8
rG4TWxN/jQKBgDBTXECurwCoX3EUVFMCGg+dYtC+UqDpTyr/LpjsGQ+uEDY276HC
DuVMmDLUGjtho/M5Xe03VR24S7Ya9i7HPt/epY0BqRWIats25W51Y3wBzKOaQVeW
4/XeDQuAJ2+dGAd8bk1mN0Gf7oiaLYSlpWXxXK5ybdctTU9nye2brCHjAoGAaY5M
iw66Py7af7CC2l1l5VmWlkL7+/jJJdIbu0wOLACeDYyUBumF6QFIW9dDRCCzLJb8
g8av5TE44sjLqjcJnq0AiGIrf5/G1x1cV6EcAGyEfFi33ILHD6OPHc1bbwv44ign
UrLtKoaTgUhdkHurbII1PaF2jJXrJxz2SDd998kCgYEA/qXmiXm78dK3jgLH17/W
6b+vk1NyVoJyv0W1aTAErJTinvcN8LvcusBeHbSY7R3zDdOsR1prW8aBqu7OHtmh
TL68OxCTxBPxEqdAgvj8lXJUW05S9oaU9O02Vqam3JJLTWhIEVpORCbphK5hqFXU
xVNYaO3Xp4LFsgUgyuCqKrQ=
-----END PRIVATE KEY-----"""
client_email = "araba2025@my-project-21182-468414.iam.gserviceaccount.com"
client_id = "116542908027882109139"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/araba2025%40my-project-21182-468414.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
